### ISSUE TITLE
Changes to control-flow within the NetLogo engine

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1071]
This incorporates a number of issues that I think need to be fixed simultaneously (or at least verified together to ensure a fix to one doesn't break another).

- [ ] `report` should be allowed inside `carefully` (formerly https://github.com/NetLogo/NetLogo/issues/322)
- [ ] `report` should be allowed inside `ask` (formerly https://github.com/NetLogo/NetLogo/issues/424)
- [ ] `stop` inside `foreach` inside `ask` confuses engine (formerly https://github.com/NetLogo/NetLogo/issues/683)

**Comment by alan-isaac** [comment]
If you are enhancing control flow, is it possible to finally have a `break` for loop constructs (including `ask`)?
